### ISSUE TITLE
API Breaking Changes Coming

### ISSUE THREAD

**Issue by kspearrin** [jcs/bitwarden-ruby#32] opened 2018-03-02 00:00 UTC
@jcs Just thought you should know that there are some breaking changes coming to cipher API models.

1. `Cipher.Login.Uri` on the request and response models is being deprecated in favor of `Cipher.Login.Uris`, an array of `{ "Uri": string, "Match": enum }`
2. The cipher response model is being updated to better match the request model. Namely:
    - `Data` prop is being deprecated.
    - Adding: `Name`, `Notes`, and `Fields` to the root object.
    - Adding: `Login`, `Card`, `Identity`, and `SecureNote` to the root object (their prop values were part of the dynamic `Data` property in the past).

Our API will handle these changes in a backwards compatible way for a few iterations since outdated client apps will still be expecting the old models for some time.

These changes are already in the `Core` API project and refactoring is being done in all client apps over the next few days.

**Comment by linktohack** [comment] 2018-03-04 15:15
Thanks for your openness @kspearrin! Cannot think you're willing to contribute to this repo!

**Comment by feld** [comment] 2018-03-20 19:53
I don't see this API change mentioned, but I am seeing this with the latest extension:

    Mar 20 19:50:16 colo bitwarden: 47.49.35.242 - - [20/Mar/2018:19:50:16 +0000] "GET /api/accounts/revision-date HTTP/1.1" 404 18 0.0008

**Comment by jcs** [comment] 2018-03-20 22:33
Please see #36 and help test these changes to work with the new upstream clients.

**Comment by raufis27** [comment] 2018-03-20 22:57
Tested Safari extension and it works. But iOS app doesn't load db anymore. It just keeps spinning.

**Comment by kspearrin** [comment] 2018-03-20 22:58
This is because mobile apps don’t have the new seat update yet. They will go out tomorrow.

**Comment by kspearrin** [comment] 2018-03-20 23:01
@raufis27 

Side note: did your safari extension auto update to 1.25.x? I've been trying to test the auto-updates there but it seems like none of my extensions every update.

**Comment by logic** [comment] 2018-03-20 23:03
FWIW, current android release crashes on sync as well, because `Data` isn't populated. It's (hopefully) a short-lived problem, but worth mentioning (and pretty easily rectified by generating a `Data` hash before sending the `cipherDetails` out the door).

The migration went perfectly for me with the auto-updated Firefox extension, and I have a... er... non-trivial database, so a big :+1: here.

**Comment by jcs** [comment] 2018-03-20 23:08
I had some code in there to supply a legacy `Data` object in the old format (as well as `Uri` from `Uris[0].Uri`) but `Cipher#update_from_params` didn't support updating records from old clients, so I took it out.  Since the new mobile clients are releasing tomorrow, I'll just wait to test with those.

**Comment by raufis27** [comment] 2018-03-20 23:12
@kspearrin I reinstalled extension. Didn't use update function.

**Comment by raufis27** [comment] 2018-03-20 23:22
Some issues: 
1. Can't add URL to item. Tried existing and new item. I see PUT request, but url not saved. 
2. Desktop app doesn't work, same problem as iOS app.

**Comment by feld** [comment] 2018-03-21 01:37
Confirmed, adding URI to an item seems to create a blank URI field.

**Comment by jcs** [comment] 2018-03-21 04:02
That should be fixed with c3e0eb1f3.  It was saving but the client was not reading it back properly because of the case.

@kspearrin It'd be really nice if all of the apps and API could agree on a case format 😀 It's odd that the browser extension sends everything in lowercase (`"login": { "uris": [ "uri":`) but then requires it back as `"Login": { "Uris": [ "Uri":`.

**Comment by kspearrin** [comment] 2018-03-21 12:41
Yea, our server is case insensitive, so I guess we get a little lax with that. :-/ ideally everything would be camel.

**Comment by jcs** [comment] 2018-03-22 02:04
Thanks for testing everyone, this functionality is now in HEAD

**Closed by jcs** 2018-03-22 02:04 UTC
Labels: testing needed, upstream-compatibility
